'use strict';

module.exports = {
  'caseSensitive': true,
  'collapseWhitespace': true,
  'includeAutoGeneratedTags': false,
  'keepClosingSlash': true,
  'minifyCSS': true,
  'minifyJS': true,
  'processConditionalComments': true,
  'removeComments': true,
};
